package com.example.nlsql.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;
import java.util.Map;

/**
 * Represents the JSON response returned to the frontend.
 *
 * Example:
 * {
 *   "sql": "SELECT * FROM users LIMIT 10",
 *   "rows": [
 *      { "id": 1, "name": "Alice" },
 *      { "id": 2, "name": "Bob" }
 *   ]
 * }
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class QueryResponse {

    /**
     * The SQL query that was generated by the LLM.
     * It is useful for transparency and debugging.
     */
    private String sql;

    /**
     * The result rows returned by executing the SQL on PostgreSQL.
     * Each map represents a single row: column name -> value.
     */
    private List<Map<String, Object>> rows;
    
    private String explanation;
    
    
    private Integer page;
    private Integer pageSize;
    private Boolean hasMore;
    
 // NEW fields for ambiguity
    private boolean clarificationNeeded;
    private String clarificationQuestion;
    
    private String status; 
    
    private String error;

}

